### ISSUE TITLE
Entity flashing forever

### ISSUE THREAD

**Issue by tacotexmex** [Noodlemire/clumpfall#2]
After a large clumpfall, the entities seem to flash back and forth forever:

https://imgur.com/a/FYk9YlU

**Comment by Noodlemire** [comment]
Is this because they were on sand? If so, this is fixed after this update. Previously, clump fall nodes couldn't use non-clump fall nodes for supports at all, meaning that they infinitely try to turn into falling node entities once disturbed. Now, they won't as long as there is any walkable node underneath them, even if those walkable nodes aren't clump fall nodes (i.e. sand, bedrock)

**Comment by tacotexmex** [comment]
Cool, I’ll try it out! Thanks for a great mod.
